### ISSUE TITLE
Client Id validation too strict

### ISSUE THREAD

**Issue by aedart** [binsoul/net-mqtt#3]
Hi @binsoul  

I have an issue with the Client Id validation, in `\BinSoul\Net\Mqtt\Packet\ConnectRequestPacket::setClientID` - it is just a bit too strict.

There are a few situation where my client id requires `_` and or `-`. This is mainly due to company naming conversion. The `ctype_alnum` check is prohibiting such.

Nevertheless, there should be an issue for client ids to contain dash and underscores (as far as I can tell).

**Comment by valga** [comment]
I second this issue. Standard says 
> The Server MAY allow ClientId’s that contain more than 23 encoded bytes. The Server MAY allow ClientId’s that contain characters not included in the list given above. 

So, basically saying, it is up to server to decide whether supplied client ID is valid or not.

**Comment by binsoul** [comment]
I tested several brokers and they all accepted client ids longer than 23 bytes containing other characters than A-Z and 0-9. So the ConnectRequestPacket class now accepts all client ids and lets the broker decide if the supplied client id is valid.

If someone really needs to enforce client ids shorter than 24 bytes containing only alphanumeric characters he can use the new StrictConnectRequestPacket class.
